version: '3.7'
services:
  mongodb_ut:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27027:27017"
    volumes:
      - mongodb_ut_data_container:/data/db

  mongodb_it:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27037:27017"
    volumes:
      - mongodb_it_data_container:/data/db

volumes:
  mongodb_ut_data_container:
  mongodb_it_data_container:
